# action.yml
name: 'Packer Ansible'
description: 'Greet someone and record the time'
inputs:
  packerfile:  # id of input
    description: 'Packer file name'
    required: true
    default: 'World'
outputs:
  ami: # id of output
    description: 'AMI ID'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.packerfile }}